fix(build): collect klayout content to avoid runtime error
Because we hadn’t fully included the KLayout packages before, we ran
into this error:

```shell
RuntimeError: Stream has unknown format:
/workspaces/chip-compiler/workspacetest/Floorplan_ecc/output/gcd_Floorplan.gds
in LayoutViewBase.load_layout
```

Signed-off-by: Emin <me@emin.chat>